global:
  scrape_interval: 5s

scrape_configs:
  - job_name: gateway-service
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names:
          - gateway-service
        type: A
        port: 8080
        refresh_interval: 5s

  - job_name: product-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - product-service:8081

  - job_name: order-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - order-service:8082
