services:
  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway-service
    environment:
      SPRING_DATA_REDIS_HOST: gateway-redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      gateway-redis:
        condition: service_healthy
    networks:
      - observability-net

  gateway-redis:
    image: redis:7-alpine
    container_name: gateway-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - observability-net

  gateway-prometheus:
    image: prom/prometheus:v2.55.1
    container_name: gateway-prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - gateway-service
    networks:
      - observability-net

  gateway-grafana:
    image: grafana/grafana:11.3.0
    container_name: gateway-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    depends_on:
      - gateway-prometheus
    networks:
      - observability-net

networks:
  observability-net:
    driver: bridge
